# Generated by Django 2.2.7 on 2019-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dest_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'dest_images',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=1)),
                ('type', models.CharField(max_length=5)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('color_histogram', models.TextField()),
                ('texture_histogram', models.TextField()),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
